#!/bin/sh

if [ -e /var/clearos/accounts/state ]; then
    logger -p local6.notice -t installer "app-accounts-core - removing state file"
    rm -f /var/clearos/accounts/state
fi

if [ -e /var/clearos/accounts/config ]; then
    logger -p local6.notice -t installer "app-accounts-core - removing config file"
    rm -f /var/clearos/accounts/config
fi

if [ -e /var/clearos/accounts/initialized ]; then
    logger -p local6.notice -t installer "app-accounts-core - removing initialized file"
    rm -f /var/clearos/accounts/initialized
fi

if [ -e /var/clearos/accounts/transaction.log ]; then
    logger -p local6.notice -t installer "app-accounts-core - removing transaction log"
    rm -f /var/clearos/accounts/transaction.log
fi

if [ -e /var/clearos/accounts/transaction.state ]; then
    logger -p local6.notice -t installer "app-accounts-core - removing transaction state"
    rm -f /var/clearos/accounts/transaction.state
fi
